//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FondoInversion
    {
        public int CodigoInversion { get; set; }
        public int CodigoCuenta { get; set; }
        public string Plazo { get; set; }
        public string Tasa { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaHoraInicio { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
    }
}
