//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marchamo
    {
        public int CodigoPago { get; set; }
        public int CodigoUsuario { get; set; }
        public string PlacaVehiculo { get; set; }
        public decimal Monto { get; set; }
        public int CodigoMoneda { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaHoraPago { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
