//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinpeMovil
    {
        public int CodigoSinpe { get; set; }
        public int CodigoUsuario { get; set; }
        public int CodigoMoneda { get; set; }
        public string NumeroTelefonoEmisor { get; set; }
        public string NumeroTelefonoRemitente { get; set; }
        public string Descripcion { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaHora { get; set; }
        public decimal Comision { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
