//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sobre
    {
        public int CodigoSobre { get; set; }
        public int CodigoCuenta { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaHoraInicio { get; set; }
        public string Frecuencia { get; set; }
        public System.DateTime FechaHoraFinal { get; set; }
        public decimal Monto { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
    }
}
