//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudCita
    {
        public int CodigoCita { get; set; }
        public int CodigoUsuario { get; set; }
        public string TipoCita { get; set; }
        public System.DateTime FechaHoraCita { get; set; }
        public string Sede { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
