//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudCita
    {
        public int CodigoCita { get; set; }
        public int CodigoUsuario { get; set; }
        public string TipoCita { get; set; }
        public System.DateTime FechaHoraCita { get; set; }
        public string Sede { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
